In [ ]:
from scipy import stats
import numpy as np
import math
import matplotlib.pyplot as plt
import random

sigmoid = (
  lambda x:1 / (1 + np.exp(-x)),
  lambda x:x * (1 - x)
  )

def derivada_relu(x):
  x[x<=0] = 0
  x[x>0] = 1
  return x

relu = (
  lambda x: x * (x > 0),
  lambda x:derivada_relu(x)
  )

def circulo(num_datos = 100,R = 1, minimo = 0,maximo= 1):
  pi = math.pi
  r = R * np.sqrt(stats.truncnorm.rvs(minimo, maximo, size= num_datos)) * 10
  theta = stats.truncnorm.rvs(minimo, maximo, size= num_datos) * 2 * pi *10
  #print(len(r))
  #print(len(theta))
  x = np.cos(theta) * r
  y = np.sin(theta) * r

  y = y.reshape((num_datos,1))
  x = x.reshape((num_datos,1))

  #Vamos a reducir el numero de elementos para que no cause un Overflow
  x = np.round(x,3)
  y = np.round(y,3)

  df = np.column_stack([x,y])
  #print(df)
  return(df)

#print(len(X))
#print(len(Y))
# Numero de neuronas en cada capa.
# El primer valor es el numero de columnas de la capa de entrada.
#neuronas = [2,4,8,1]

# Funciones de activacion usadas en cada capa.
#funciones_activacion = [relu,relu, sigmoid]

#red_neuronal = []

#for paso in range(len(neuronas)-1):
#  x = capa(neuronas[paso],neuronas[paso+1],funciones_activacion[paso])
#  print(neuronas[paso],neuronas[paso+1],funciones_activacion[paso])

#  red_neuronal.append(x)
#  print(x)

#print(red_neuronal)


def mse(Ypredich, Yreal):

  # Calculamos el error
  #print(Ypredich)
  #print(Yreal)
  x = (np.array(Ypredich) - np.array(Yreal)) ** 2
  #print(x)
  x = np.mean(x)
  #print(x)
  # Calculamos la derivada de la funcion
  y = np.array(Ypredich) - np.array(Yreal)
  return (x,y)


def entrenamiento(epoch, X,Y, red_neuronal, lr = 0.01):

  # Output guardara el resultado de cada capa
  # En la capa 1, el resultado es el valor de entrada
  output = [X]
  for num_capa in range(len(red_neuronal)):
    z = output[-1] @ red_neuronal[num_capa].W + red_neuronal[num_capa].b
    a = red_neuronal[num_capa].funcion_act[0](z)
    #print(epoch)
    #if (epoch==0) or (epoch==-999):
      #print(epoch)
      #print(red_neuronal[num_capa].funcion_act[0]( np.array([-1, 1]) ))
      #print(X, X.shape)
      #print('w', red_neuronal[num_capa].W.shape)
      #print(red_neuronal[num_capa].W)
      #print('b', red_neuronal[num_capa].b.shape)
      #print(red_neuronal[num_capa].b)

      #print('z', z.shape)
      #print(z)
      #print('act ', num_capa)
      #print(a)
    # Incluimos el resultado de la capa a output
    output.append(a)

  # Backpropagation

  back = list(range(len(output)-1))
  back.reverse()

  # Guardaremos el error de la capa en delta
  delta = []

  for capa in back:
    # Backprop #delta

    a = output[capa+1]
    #if (epoch==0) or (epoch==-999):
    #  print('activation', a)

    if capa == back[0]:
      x = mse(a,Y)[1] * red_neuronal[capa].funcion_act[1](a)
      delta.append(x)
      #if (epoch==0) and (epoch==-999):
      #  print('mse 0', x)
        #print('mse 01', mse(a,Y)[1] )
        #print('mse 02', red_neuronal[capa].funcion_act[1](a) )
        #print('mse 02', red_neuronal[capa].funcion_act[1](np.array([-2, -1, 0, 1, 2])) )

    else:
      #if (epoch==0) and (capa == back[1]):
      #  print('function a ', a)
      #  print('delta', delta[-1])
      #  print('W_temp', W_temp)

      x = delta[-1] @ W_temp * red_neuronal[capa].funcion_act[1](a)
      #if (epoch==0) and (capa == back[1]):
      #  print('x ', x)

      delta.append(x)

 #       print('mse 2', x)

    W_temp = red_neuronal[capa].W.transpose()
    #if (epoch==0) or (epoch==-999):
    #  print('W_temp', capa, red_neuronal[capa].W, W_temp)
    # Gradient Descent #
    red_neuronal[capa].b = red_neuronal[capa].b - np.mean(delta[-1], axis = 0, keepdims = True) * lr
    red_neuronal[capa].W = red_neuronal[capa].W - output[capa].transpose() @ delta[-1] * lr
    #if (epoch==0) and (capa==0):
    #  print('output 0', output[capa].transpose())
    #  print('delta  0', delta[-1])

    #print(red_neuronal[capa].W)
    #print('b', capa)
    #print(red_neuronal[capa].b)

  return output[-1]

class capa():
  def __init__(self, n_neuronas_capa_anterior, n_neuronas, funcion_act):
    self.funcion_act = funcion_act
    #self.b  = np.round(stats.truncnorm.rvs(-1, 1, loc=0, scale=1, size= n_neuronas).reshape(1,n_neuronas),3)
    #self.W  = np.round(stats.truncnorm.rvs(-1, 1, loc=0, scale=1, size= n_neuronas * n_neuronas_capa_anterior).reshape(n_neuronas_capa_anterior,n_neuronas),3)
    self.b  = np.full((1,n_neuronas), 0.25).reshape(1,n_neuronas)
    self.W  = np.full((1,n_neuronas * n_neuronas_capa_anterior), 0.75).reshape(n_neuronas_capa_anterior,n_neuronas)


N=150

datos_1 = circulo(num_datos = N, R = 2)
datos_2 = circulo(num_datos = N, R = 0.5)
#X = np.concatenate([datos_1,datos_2])
#X = np.round(X,3)

X = np.array([ [19.467222027313564, -99.12219861354929],
[19.482265616680536, -99.14190350018883],
[19.476990639248996, -99.13936414016929],
[19.462926665702092,  -99.14510100533802],
[19.465871557932942, -99.1367188182426],
[19.47237365730388, -99.14509978671352],
[19.464066506396268, -99.13291715146295],
[19.462052618719053, -99.15092596673614],
[19.474422807391647,  -99.1438514157048],
[19.47237241832461,  -99.14570383179539],
[19.450085377691707,  -99.12859837428849],
[19.479921790581052,  -99.14667476345326],
[19.453633512514266, -99.13628285667163],
[19.472190658390566, -99.14982956004451],
[19.47395263950297,  -99.15101797733233],
[19.465252402898983, -99.13898902224867],
[19.461874805051114, -99.14515853743147],
[19.469209782455476, -99.14038136552176],
[19.45741613536277, -99.13686213058105],
[19.47421974621611,  -99.14489828681003],
[19.4662759012438, -99.14030630674392],
[19.448275401978687, -99.14286578386036],
[19.469434885003373, -99.12735700514285],
[19.4749361786807, -99.12654419193377],
[19.47997289288032, -99.1420344373171],
[19.46620589351966, -99.1399694994465],
[19.476580907985532, -99.11686758601223],
[19.461851297630492, -99.11433631660428],
[19.47705057940435, -99.13037438935557],
[19.470577377784227, -99.14363811186868],
[19.485601032367263, -99.13049711986271],
[19.48488889230067, -99.14022466504971],
[19.485374180852496, -99.14287379001047],
[19.456310798085966, -99.13839232623272],
[19.48251305339346, -99.15563537453852],
[19.46434471028183, -99.15938312521207],
[19.483425965849538, -99.14328489662618],
[19.486761037171586, -99.12334701629308],
[19.46373747465879, -99.14451466137191],
[19.492836626097954, -99.14572553222457],
[19.480573183372517, -99.13361184936554],
[19.470533864108532, -99.13831201601843],
[19.45475663149979, -99.1491266977481],
[19.476944101951492, -99.14168910044891],
[19.477627432637608, -99.12478839083609],
[19.482843060414048, -99.12177061779703],
[19.45800204716716, -99.1537745992418],
[19.477638425080112, -99.12917924626362],
[19.44533463361916, -99.13309049585013],
[19.478332736736117, -99.14238543333826],
[19.480407845952456,  -99.13212449743668],
[19.46952412138314, -99.13212341424693],
[19.46307806743916, -99.13591274724371],
[19.470269228564263, -99.15138468780052],
[19.47141503394753, -99.15805636444716],
[19.478786673898128, -99.14103062705644],
[19.4600628206952, -99.1487776814693],
[19.48606379324133, -99.14890239835681],
[19.478509323583307, -99.13233925815327],
[19.469865121840453, -99.13786958474182],
[19.484410537831664, -99.121693317719],
[19.463341465865337, -99.14914795126047],
[19.482818358842174, -99.14082501341082],
[19.46631819489393, -99.12469562596752],
[19.475618269619783, -99.14759375080713],
[19.4627645651239, -99.14233753011449],
[19.479120452840874, -99.12567981733912],
[19.46159647701849, -99.14470594514692],
[19.460079605655718, -99.14741174919547],
[19.476569829600766, -99.1440625767766],
[19.46987021440519, -99.14082658791264],
[19.48310472340533, -99.14065797396451],
[19.491908108199073, -99.1339835131305],
[19.485375544210143, -99.1312665165737],
[19.454031977970253, -99.15422455705304],
[19.452497279136075, -99.1292192022765],
[19.458765579991933, -99.14229789199116],
[19.476354588347395, -99.13929907806016],
[19.453320804423655, -99.14549547326418],
[19.48430362904814, -99.14006115004362],
[19.47752750177724, -99.13758299444518],
[19.47394999145678, -99.15293220683569],
[19.473968111959614, -99.12710937533065],
[19.47073051061994, -99.13369236987343],
[19.46441825443714, -99.12927833217012],
[19.483484533257922, -99.1381563214215],
[19.478196301055913, -99.14284986255021],
[19.446308912122177, -99.15706179393689],
[19.469231275602365, -99.14556403154653],
[19.483542086031548, -99.14131650827791],
[19.452873444162485, -99.1488118060631],
[19.479762408497173, -99.16505535513419],
[19.471954180014556, -99.12756997624093],
[19.48536406020416, -99.16225064849888],
[19.482358721278874,-99.16658050278602],
[19.472306443209774, -99.14502501477897],
[19.4834665609573, -99.14972179568096],
[19.464543085286973, -99.13503426531007],
[19.46504234959824, -99.13343340206148],
[19.4775589850638, -99.11377193934732],
[19.495660202980694, -99.13698606395911],
[19.46295217503846, -99.14070137784498],
[19.469937918466062, -99.14987218558234],
[19.46112726603321, -99.14538049221726],
[19.461849710301273, -99.11957394173729],
[19.457231790616685, -99.13052646998139],
[19.47274660283314, -99.13548709955731],
[19.46180004259595, -99.11946493999424],
[19.480188978035688,  -99.12285249689992],
[19.470279254192434, -99.14223773313448],
[19.483522121895632, -99.1428242942711],
[19.46169098094029, -99.156447602285],
[19.47291209620327, -99.12104964668455],
[19.467375582337734, -99.14765867916736],
[19.462683049121033, -99.12197320532583],
[19.452591058010732, -99.15353925580074],
[19.466176632311498, -99.13575398512884],
[19.465003853375855, -99.13827391845079],
[19.467683711489805, -99.15023940496367],
[19.46604724124821, -99.15100221793305],
[19.469432182844546, -99.13279593990224],
[19.460565817854008, -99.13170909287767],
[19.473834734898436, -99.1406158331018],
[19.482649974744792, -99.13438872188017],
[19.475119593373265, -99.14513081463329],
[19.469870302031687, -99.14356074939323],
[19.474586644292575, -99.13187908048549],
[19.469327348222564, -99.13515743581809],
[19.47790601014896, -99.13136064597589],
[19.47087371489028, -99.14865738633189],
[19.47402729671688, -99.11803399866842],
[19.471919731477428, -99.13869444396676],
[19.500248069980504, -99.13623631436498],
[19.49119403508465, -99.13472739147869],
[19.474806930618012, -99.14152343688409],
[19.46466055346265, -99.14019832335595],
[19.472788390864512, -99.13777561964021],
[19.487132603734175, -99.14423144873417],
[19.480733763811138, -99.13486790976509],
[19.451318874994854, -99.13576177078268],
[19.46901379636231, -99.13919133175108],
[19.475683358385, -99.13815038927078],
[19.4694098141617, -99.11967060662623],
[19.45878068199157, -99.15470878657582],
[19.472758275068117, -99.1134313956857],
[19.46116145706365, -99.14744317356524],
[19.46360146156197, -99.15796316868236],
[19.44585269034688, -99.12596080046318],
[19.46572005748166, -99.12553949026378],
[19.45951811724063, -99.15072502741356],
[	48.53384067	,	2.617842798	],
[	48.55115296	,	2.600669664	],
[	48.54813041	,	2.606115161	],
[	48.53583182	,	2.611454369	],
[	48.559793	,	2.593962223	],
[	48.52921008	,	2.600309074	],
[	48.5329234	,	2.632414196	],
[	48.5248124	,	2.613880403	],
[	48.52508281	,	2.608197471	],
[	48.54618928	,	2.632532141	],
[	48.55017127	,	2.612889924	],
[	48.55329165	,	2.616240916	],
[	48.53826385	,	2.616131205	],
[	48.53296758	,	2.612200908	],
[	48.55009432	,	2.603417464	],
[	48.53494555	,	2.616196208	],
[	48.54160127	,	2.625886265	],
[	48.52622097	,	2.601108655	],
[	48.53990201	,	2.599727329	],
[	48.54242181	,	2.614200374	],
[	48.552599	,	2.618122468	],
[	48.56590669	,	2.607144935	],
[	48.54134209	,	2.612875555	],
[	48.54503743	,	2.624234055	],
[	48.53197892	,	2.62154926	],
[	48.53550167	,	2.611253737	],
[	48.54020758	,	2.621302426	],
[	48.52552935	,	2.618951447	],
[	48.5292991	,	2.61063329	],
[	48.56056865	,	2.614341636	],
[	48.52918456	,	2.605839083	],
[	48.54651169	,	2.621330142	],
[	48.53842127	,	2.618265475	],
[	48.53432506	,	2.605732892	],
[	48.54955589	,	2.586225671	],
[	48.5243268	,	2.608772515	],
[	48.53956295	,	2.599834673	],
[	48.51105944	,	2.598971143	],
[	48.54395737	,	2.607186365	],
[	48.53031823	,	2.61155845	],
[	48.53647776	,	2.61007146	],
[	48.54258374	,	2.593789711	],
[	48.53431442	,	2.593348447	],
[	48.54748668	,	2.606374703	],
[	48.54229094	,	2.630238881	],
[	48.53477394	,	2.629015649	],
[	48.52939976	,	2.601539412	],
[	48.52004916	,	2.610331281	],
[	48.56286461	,	2.606454216	],
[	48.55159687	,	2.616337417	],
[	48.53984464	,	2.624141639	],
[	48.52604818	,	2.624000305	],
[	48.54340964	,	2.638943188	],
[	48.54123961	,	2.607130876	],
[	48.54104207	,	2.611851208	],
[	48.53325229	,	2.596489525	],
[	48.5433949	,	2.59340789	],
[	48.534982	,	2.623385524	],
[	48.53346767	,	2.619490833	],
[	48.53116627	,	2.603992072	],
[	48.54015414	,	2.608244561	],
[	48.54092784	,	2.624908362	],
[	48.5398258	,	2.597574304	],
[	48.55641658	,	2.618147862	],
[	48.54337243	,	2.608763414	],
[	48.52615408	,	2.618201969	],
[	48.54330798	,	2.61260355	],
[	48.53946122	,	2.640925838	],
[	48.55149401	,	2.613307132	],
[	48.56135061	,	2.604478256	],
[	48.53885218	,	2.600737021	],
[	48.5358474	,	2.618817655	],
[	48.54598594	,	2.617689781	],
[	48.53501891	,	2.610599727	],
[	48.53763575	,	2.610894493	],
[	48.53732356	,	2.609436313	],
[	48.53594999	,	2.608506556	],
[	48.55031254	,	2.613848245	],
[	48.54431132	,	2.615636437	],
[	48.54002501	,	2.611736172	],
[	48.52011725	,	2.593790632	],
[	48.54046159	,	2.602653724	],
[	48.53415504	,	2.61265933	],
[	48.53029397	,	2.618245445	],
[	48.53545931	,	2.60312646	],
[	48.54686619	,	2.597532983	],
[	48.54107798	,	2.607280066	],
[	48.54881477	,	2.614390014	],
[	48.54228478	,	2.607324119	],
[	48.54201961	,	2.610985464	],
[	48.54283699	,	2.615038748	],
[	48.54376187	,	2.616549999	],
[	48.55128933	,	2.606038894	],
[	48.54423832	,	2.610428913	],
[	48.53256951	,	2.604212426	],
[	48.5320656	,	2.604583687	],
[	48.54409272	,	2.638649864	],
[	48.5514997	,	2.611232202	],
[	48.53746568	,	2.607886336	],
[	48.53471379	,	2.628613672	],
[	48.53539181	,	2.603766975	],
[	48.52281858	,	2.622096467	],
[	48.54275383	,	2.613571291	],
[	48.53808075	,	2.625956095	],
[	48.54475149	,	2.623037493	],
[	48.55530759	,	2.60753	],
[	48.5371911	,	2.605349154	],
[	48.54797101	,	2.603331719	],
[	48.53487689	,	2.602290789	],
[	48.53119854	,	2.60174092	],
[	48.5418094	,	2.621086763	],
[	48.53697317	,	2.601252107	],
[	48.54125637	,	2.609791619	],
[	48.53372287	,	2.612387855	],
[	48.55283425	,	2.608123374	],
[	48.53808367	,	2.615505203	],
[	48.53225517	,	2.600340025	],
[	48.54938105	,	2.631928007	],
[	48.54238848	,	2.624814728	],
[	48.5271638	,	2.598368582	],
[	48.54088154	,	2.605746112	],
[	48.54417127	,	2.611542869	],
[	48.54169212	,	2.59920863	],
[	48.54297979	,	2.614172614	],
[	48.55451867	,	2.624969916	],
[	48.54013272	,	2.623996907	],
[	48.53573374	,	2.613994653	],
[	48.5200309	,	2.60802105	],
[	48.54560615	,	2.607420477	],
[	48.54585471	,	2.616360689	],
[	48.52540245	,	2.602603841	],
[	48.53987204	,	2.603320273	],
[	48.5532735	,	2.604968681	],
[	48.51808581	,	2.613234121	],
[	48.56152477	,	2.616037593	],
[	48.55386902	,	2.621139161	],
[	48.53176506	,	2.611822468	],
[	48.55172991	,	2.613272924	],
[	48.55016767	,	2.617837218	],
[	48.53475022	,	2.609472833	],
[	48.54709553	,	2.616779019	],
[	48.54656873	,	2.611303596	],
[	48.52371716	,	2.611986677	],
[	48.54367431	,	2.614694333	],
[	48.53012162	,	2.634398603	],
[	48.53188729	,	2.608154232	],
[	48.54428816	,	2.602299928	],
[	48.52500598	,	2.614197207	],
[	48.5465352	,	2.608028039	],
[	48.55526452	,	2.612763409	]
             ])

Y = [0] * N + [1] * N
Y = np.array(Y).reshape(len(Y),1)

#print('labels')
#print(Y)

neuronas = [2,4,8,1]
funciones_activacion = [relu,relu, sigmoid]
red_neuronal = []

for paso in list(range(len(neuronas)-1)):
  x = capa(neuronas[paso],neuronas[paso+1],funciones_activacion[paso])
  red_neuronal.append(x)
  #print('w')
  #print(neuronas[paso])
  #print(neuronas[paso+1])

  #print(x.W)
  #print('b')
  #print(x.b)
  #print('---')
error = []
predicciones = []

for epoch in range(0, 100):
  ronda = entrenamiento(epoch, X = X ,Y = Y ,red_neuronal = red_neuronal, lr = 0.001)
  #print('-----')
  #print(ronda)
  #print(Y)
  predicciones.append(ronda)
  temp = mse(np.round(predicciones[-1]),Y)[0]
  #print(temp)
  #print('-----')
  error.append(temp)


#print('===final Y1 =====')
#print(predicciones[-1][0:N])
#print('===final Y2 =====')
#print(predicciones[-1][N:N*2])

#print(Y)

print('w 0')
print(red_neuronal[-3].W)
print('b 0')
print(red_neuronal[-3].b)

print('w 1')
print(red_neuronal[-2].W)
print('b 1')
print(red_neuronal[-2].b)


print('w 2')
print(red_neuronal[-1].W)
print('b 2')
print(red_neuronal[-1].b)



#epoch = list(range(0,1))
#plt.cla()
#plt.plot(epoch, error)],

w 0
[[0.75 0.75 0.75 0.75]
 [0.75 0.75 0.75 0.75]]
b 0
[[0.25 0.25 0.25 0.25]]
w 1
[[0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75]
 [0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75]
 [0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75]
 [0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75]]
b 1
[[0.2466734 0.2466734 0.2466734 0.2466734 0.2466734 0.2466734 0.2466734
  0.2466734]]
w 2
[[0.26303472]
 [0.26303472]
 [0.26303472]
 [0.26303472]
 [0.26303472]
 [0.26303472]
 [0.26303472]
 [0.26303472]]
b 2
[[0.24345709]]
